apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: c2VjcmV0
  openai-api-key: c2stcUlUbkNOT3Q3QVhJV3B5S0JnTVRUM0JsYmtGSk9IOXp4UDJMRTBlT1NXT2FqQW4z