apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaist-chatbot-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{.Values.app.ingress.host}}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{.Values.app.service.name}}
              port:
                number: 80
        - path: /login/
          pathType: Prefix
          backend:
            service:
              name: {{.Values.app.service.name}}
              port:
                number: 80
        - path: /signup/
          pathType: Prefix
          backend:
            service:
              name: {{.Values.app.service.name}}
              port:
                number: 80
        - path: /question/
          pathType: Prefix
          backend:
            service:
              name: {{.Values.app.service.name}}
              port:
                number: 80
  - host: mongoexpress.tdt
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{.Values.dbUI.service.name}}
              port:
                number: 8081