apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  database_url: "mongodb://mongodb-service:27017/"