apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  database_url: "mongodb://mongo-0.mongodb-service.default.svc.cluster.local,mongo-1.mongodb-service.default.svc.cluster.local,mongo-2.mongodb-service.default.svc.cluster.local:27017/"