# mongo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: {{.Values.db.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.db.name}}
  template:
    metadata:
      labels:
        app: {{.Values.db.name}}
    spec:
      containers:
      - name: {{.Values.db.name}}
        image: "{{.Values.db.image.name}}:{{.Values.db.image.tag}}"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INIT_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mongo-root-username
        - name: MONGO_INIT_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: {{.Values.db.service.name}}
  labels:
    app: {{.Values.db.name}}
spec:
  selector:
    app: {{.Values.db.name}}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

