apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mongo-pvc
spec:
  storageClassName: ""
  volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi