apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: c2VjcmV0
  openai-api-key: c2stODF0djFmaE5KRHd1NU84Zm11OE1UM0JsYmtGSkNib3gwQUQzMVZ0d3JPWDdDQmQy
  # openai-api-key: c2stcUlUbkNOT3Q3QVhJV3B5S0JnTVRUM0JsYmtGSk9IOXp4UDJMRTBlT1NXT2FqQW4z